### ISSUE TITLE
H3Grid output from LatLng inconsistent with other libraries 

### ISSUE THREAD

**Issue by ChrisJH1** [pocketken/H3.net#120]
Apologies I am new to geospatial processing and I am assuming that H3 Grid Identification should be consistent across libraries.  Specifically, when passing a latlng to the H3Index.FromLatLng(latlng, 11); the output grid, when processed via other H3 libraries python etc comes back with a very different Lat lon. This was discovered as I have a large volume of data matched to H3 via other libraries and my whilst processing incoming lat lons via my api I noticed zero collisions. example points below:   
 lat of 51.524742 and lon of -0.081056
yield 8b0731931c96fff via H3Index above.

python method below  - 
Define the H3 grid cell
    h3_cell = '8b0731931c96fff'

Convert the H3 cell to latitude and longitude coordinates
     lat, lon = h3.h3_to_geo(h3_cell)

Print the latitude and longitude
      print(f"{lat}, {lon}")
72.15039941409432, -4.643722847528908

**Comment by pocketken** [comment]
Hi @ChrisJH1, just to confirm you are talking about `LatLng` and you are accounting for radians vs. degrees as noted [here](https://github.com/pocketken/H3.net/blob/main/docs/api-indexing.md#fromto-geospatial-coordinates)?

Essentially, the H3 library's `LatLng` class (which matches the upstream library's implementation) expects radians.  If you'd like to use degrees instead of radians, you can use `FromPoint` or `Coordinate.ToH3Index()` (extension method on NTS coordinates):

```cs
// from lon/lat, with a resolution of 9 -- note NTS Coordinates are longitude (X) first,
// latitude (Y) second, unlike upstream/Model.LatLng which is latitude then longitude
// (AND in radians, not degrees).
var coordinate = new Coordinate(-122.40898669969357, 37.81331899988944);
var index = coordinate.ToH3Index(9);
```

**Comment by pocketken** [comment]
I meant to say, yes -- output should match the other H3 implementations, with the caveat that I have yet to release an update that aligns with 4.1.0, so, technically until I get a release with #86 out the door you could have some slight differences for some cells due to the precision change in upstream 4.0.1+.  I've got it implemented in another branch, I just hadn't had time a of yet to wrap up that work and actually get the release out.  I'm going to try and do that in the coming weeks.

**Comment by ChrisJH1** [comment]
Many apologies for the time waste here - degree vs radians was indeed the issue. 
Many thanks for the swift response and I will try to read the documentation more next time!

**Comment by pocketken** [comment]
No worries, @ChrisJH1, just glad to see you're sorted.

The radians vs. degrees thing has actually come up a few times, so, I'll put it on my todo list to make the documentation a little more obvious/explicit in this regard as part of the next release.
